export type DirectionTypes = "in" | "out" | "both";

export type PropertyTypes =
  | "integer"
  | "decimal"
  | "string"
  | "boolean"
  | "date"
  | "datetime"
  | "time"
  | "timestamp"
  | "relation"
  | "enum";

export type TokensName =
  | "NodeReserved"
  | "RelationshipReserved"
  | "EnumReserved"
  | "StringReserved"
  | "IntegerReserved"
  | "DecimalReserved"
  | "DateTimeReserved"
  | "DateReserved"
  | "TimeReserved"
  | "LocationReserved"
  | "RelationReserved"
  | "RelationArgNameReserved"
  | "RelationArgDirectionReserved"
  | "DirectionINReserved"
  | "DirectionOUTReserved"
  | "DirectionBOTHReserved"
  | "Identifier"
  | "Colon"
  | "Comma"
  | "OpeningBrace"
  | "ClosingBrace"
  | "OpeningBracket"
  | "ClosingBracket"
  | "OpeningParenthesis"
  | "ClosingParenthesis"
  | "FunctionOperator"
  | "OptionalOperator"
  | "whitespace"
  | "StringLiteral"
  | "StringLiteral"
  | "IntegerLiteral"
  | "DecimalLiteral"
  | "DateLiteral"
  | "DateTimeLiteral"
  | "TimeLiteral"
  | "LocationLiteral"
  | "Comment";
